point_cloud_topic: "/point_cloud/cloud_registered"
map_frame_id: "odom"
robot_base_frame_id: "zed_camera"
robot_pose_with_covariance_topic: "/pose_g"
robot_pose_cache_size: 200
track_point_frame_id: "zed_camera"
sensor_frame_id: "zed_left_camera"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
